[workspace]
resolver = "2"
members = [
    "crates/metatorio-solver",
    "crates/metatorio-egui",
    "crates/egui-logger",
    "crates/metatorio-data",
    "crates/metatorio-data-codegen", 
    "crates/metatorio-core",
    "crates/metatorio-runtime",
    "metatorio-app/src-tauri",
]
default-members = [
    "crates/metatorio-egui",
]
