[package]
name = "metatorio"
version = "1.2.50"
edition = "2024"

[dependencies]
dirs = "6"
dyn-clone = "1"
eframe = { version = "0.33" }
egui = { version = "0.33", features = ["rayon"] }
egui-toast = "0.19"
egui_dnd = "0.14"
egui_extras = { version = "0.33", features = ["file", "image"] }
egui_logger = { version = "0.1.0", path = "egui_logger" }
fontdb = "0.23"
good_lp = { git = "https://github.com/cyx2015s/good_lp", branch = "inspect_constraint", default-features = false, features = ["microlp"] }
image = { version = "0.25", default-features = false, features = ["png", "rayon"] }
indexmap = { version = "2", features = ["rayon", "serde"] }
log = "0.4"
mimalloc = "0.1"
rayon = "1"
regex = "1"
reqwest = { version = "0.13", default-features = false, features = ["blocking", "rustls"] }
rfd = "0.16"
self_update = "0.42"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
serde_with = "3"
tempfile = "3"
typetag = "0.2"

[build-dependencies]
winresource = "0.1"
# build.rs

[features]
default = []
wgpu = ["eframe/wgpu"]
