[package]
name = "egui_logger"
version = "0.1.0"
edition = "2024"

[dependencies]
log = "0.4"
egui = "0.33"
regex = "1.12"
puffin = { version = "0.19",  optional = true }
chrono = { version = "0.4", default-features = false, features = ["alloc", "clock"] }

[dev-dependencies]
eframe = "0.33"
multi_log = "0.1"
env_logger = "0.11"
puffin_egui = { version = "0.29.0" }
