use serde::Deserialize;

use crate::ctx::factorio::{
    common::{BoundingBox, EnergyAmount, PrototypeBase, as_vec_or_empty, option_as_vec_or_empty},
    recipe::RecipeResult,
};

pub(crate) const ENTITY_TYPES: &[&str] = &[
    "arrow",
    "artillery-flare",
    "artillery-projectile",
    "beam",
    "character-corpse",
    "cliff",
    "corpse",
    "rail-remnants",
    "deconstructible-tile-proxy",
    "entity-ghost",
    "accumulator",
    "agricultural-tower",
    "artillery-turret",
    "asteroid-collector",
    "asteroid",
    "beacon",
    "boiler",
    "burner-generator",
    "cargo-bay",
    "cargo-landing-pad",
    "cargo-pod",
    "character",
    "arithmetic-combinator",
    "decider-combinator",
    "selector-combinator",
    "constant-combinator",
    "container",
    "logistic-container",
    "infinity-container",
    "temporary-container",
    "assembling-machine",
    "rocket-silo",
    "furnace",
    "display-panel",
    "electric-energy-interface",
    "electric-pole",
    "unit-spawner",
    "capture-robot",
    "combat-robot",
    "construction-robot",
    "logistic-robot",
    "fusion-generator",
    "fusion-reactor",
    "gate",
    "generator",
    "heat-interface",
    "heat-pipe",
    "inserter",
    "lab",
    "lamp",
    "land-mine",
    "lightning-attractor",
    "linked-container",
    "market",
    "mining-drill",
    "offshore-pump",
    "pipe",
    "infinity-pipe",
    "pipe-to-ground",
    "player-port",
    "power-switch",
    "programmable-speaker",
    "proxy-container",
    "pump",
    "radar",
    "curved-rail-a",
    "elevated-curved-rail-a",
    "curved-rail-b",
    "elevated-curved-rail-b",
    "half-diagonal-rail",
    "elevated-half-diagonal-rail",
    "legacy-curved-rail",
    "legacy-straight-rail",
    "rail-ramp",
    "straight-rail",
    "elevated-straight-rail",
    "rail-chain-signal",
    "rail-signal",
    "rail-support",
    "reactor",
    "roboport",
    "segment",
    "segmented-unit",
    "simple-entity-with-owner",
    "simple-entity-with-force",
    "solar-panel",
    "space-platform-hub",
    "spider-leg",
    "spider-unit",
    "storage-tank",
    "thruster",
    "train-stop",
    "lane-splitter",
    "linked-belt",
    "loader-1x1",
    "loader",
    "splitter",
    "transport-belt",
    "underground-belt",
    "turret",
    "ammo-turret",
    "electric-turret",
    "fluid-turret",
    "unit",
    "valve",
    "car",
    "artillery-wagon",
    "cargo-wagon",
    "infinity-cargo-wagon",
    "fluid-wagon",
    "locomotive",
    "spider-vehicle",
    "wall",
    "fish",
    "simple-entity",
    "tree",
    "plant",
    "explosion",
    "fire",
    "stream",
    "highlight-box",
    "item-entity",
    "item-request-proxy",
    "lightning",
    "particle-source",
    "projectile",
    "resource",
    "rocket-silo-rocket",
    "rocket-silo-rocket-shadow",
    "smoke-with-trigger",
    "speech-bubble",
    "sticker",
    "tile-ghost",
];

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct EntityPrototype {
    #[serde(flatten)]
    pub(crate) base: PrototypeBase,

    heating_energy: EnergyAmount,

    collision_box: BoundingBox,
}

#[derive(Debug, Clone, Deserialize)]
pub(crate) struct MiningProperty {
    pub(crate) mining_time: f64,

    #[serde(deserialize_with = "option_as_vec_or_empty")]
    pub(crate) results: Option<Vec<RecipeResult>>,

    pub(crate) result: Option<String>,
    pub(crate) count: Option<f64>,

    pub(crate) fluid_amount: Option<f64>,
    pub(crate) required_fluid: Option<String>,
}
