//! Rust 代码生成：组件结构体 + 原型注册表。

use crate::config::Config;
use crate::schema::{ComplexValue, DefaultValue, Property, Prototype, Schema, TypeRef};
use crate::type_map::{self, Mapped};
use serde_json::Value;
use std::collections::{BTreeMap, HashSet};

/// 生成统计（供自检测试断言）。
#[derive(Debug, Clone, Default)]
pub struct GenStats {
    /// 生成的原型（含继承链上的抽象层）组件数。
    pub component_structs: usize,
    /// 生成的嵌套 struct 类型数。
    pub nested_structs: usize,
    /// 生成的字段总数。
    pub fields: usize,
    /// 跳过的字段数（忽略类型 / literal 常量 / 无法映射）。
    pub skipped_fields: usize,
    /// 关注的原型类型数（dump 顶层键）。
    pub concerned_typenames: usize,
    /// 生成时依赖的自定义类型名集合（如 EnergyAmount）。
    pub custom_types_used: Vec<String>,
    /// 锁定默认值的字段数（Literal 标量默认 → 非 Option）。
    pub locked_defaults: usize,
    /// 使用宽松反序列化的整数字段数。
    pub lenient_int_fields: usize,
    /// 使用宽松 Vec（内联函数或宏函数）的数组字段数。
    pub lenient_vec_fields: usize,
}

/// 组合字段组：多个原型链层重复声明的整组字段，提取为独立 Component。
#[derive(Debug, Clone)]
pub struct Composite {
    /// 组件名（如 "Icon" → IconComponent）。
    pub name: String,
    /// 组内字段名。
    pub fields: Vec<String>,
    /// 命中层（schema 类型名）：这些层用 `#[serde(flatten)]` 引用该组件。
    pub layers: HashSet<String>,
    /// 组内字段的 Property（取自第一个命中层，类型已跨层一致性校验）。
    pub properties: Vec<Property>,
}

/// 检测组合字段组：遍历所有原型（含抽象层）的**自身**属性，
/// 找出同时声明整组字段且映射类型一致的层；层数 ≥ 阈值则提取。
fn detect_composites(schema: &Schema, config: &Config) -> Vec<Composite> {
    let mut out = Vec::new();
    for (name, fields) in &config.composite_field_groups {
        let mut candidates: Vec<(&Prototype, Vec<Mapped>, Vec<Property>)> = Vec::new();
        for p in &schema.prototypes {
            let all_present = fields.iter().all(|f| {
                p.properties
                    .iter()
                    .any(|pr| &pr.base.name == f && config.field_rule(&p.base.name, f).is_none())
            });
            if all_present {
                let props: Vec<Property> = fields
                    .iter()
                    .map(|f| {
                        p.properties
                            .iter()
                            .find(|pr| &pr.base.name == f)
                            .cloned()
                            .expect("字段存在性已校验")
                    })
                    .collect();
                let mappings: Vec<Mapped> = props
                    .iter()
                    .map(|pr| type_map::map(schema, config, &pr.type_))
                    .collect();
                candidates.push((p, mappings, props));
            }
        }
        // 类型一致性：映射结果跨层必须一致（Mapped 的 Debug 作为键）
        let first_key = candidates.first().map(|(_, m, _)| format!("{m:?}"));
        let consistent: Vec<_> = candidates
            .into_iter()
            .filter(|(_, m, _)| Some(format!("{m:?}")) == first_key)
            .collect();
        if consistent.len() >= config.composite_min_layers {
            let (_, _, props) = &consistent[0];
            out.push(Composite {
                name: name.clone(),
                fields: fields.clone(),
                layers: consistent
                    .iter()
                    .map(|(p, _, _)| p.base.name.clone())
                    .collect(),
                properties: props.clone(),
            });
        }
    }
    out
}

/// 生成器入口：返回生成的 Rust 代码文本与统计。
pub fn generate(schema: &Schema, config: &Config) -> (String, GenStats) {
    let mut stats = GenStats::default();
    let mut out = String::new();

    out.push_str("// @generated by metatorio-data-codegen — DO NOT EDIT.\n");
    out.push_str("// 来源: prototype-api.json (");
    out.push_str(&schema.application_version);
    out.push_str(", api_version ");
    out.push_str(&schema.api_version.to_string());
    out.push_str(")\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n");
    out.push_str("use std::collections::BTreeMap;\n\n");

    // 1. 收集关注原型（按 typename）
    let mut concerned: Vec<&Prototype> = Vec::new();
    for tn in &config.concerned_typenames {
        if let Some(p) = schema.prototype_by_typename(tn)
            && !concerned.iter().any(|x| x.base.name == p.base.name)
        {
            concerned.push(p);
        }
    }
    stats.concerned_typenames = concerned.len();

    // 2. 收集可达 struct 类型（从所有关注原型的字段类型出发）
    let mut type_roots: Vec<String> = Vec::new();
    for p in &concerned {
        for layer in schema.prototype_chain(p) {
            for prop in &layer.properties {
                collect_type_names(&prop.type_, &mut type_roots);
            }
        }
    }
    let struct_types =
        type_map::collect_struct_types(schema, config, type_roots.iter().map(|s| s.as_str()));

    // 3. 死类型修剪：只生成"被实际生成字段引用"的嵌套类型。
    //    收集阶段（collect_struct_types）会包含被忽略字段引用的类型
    //    （如 graphics_set 里的 GraphicsSet 家族、union 的 struct 变体），
    //    这里按字段映射结果（忽略的字段不产生引用）做引用传播。
    let composites = detect_composites(schema, config);
    // 候选集：全部潜在生成类型名（链层组件 + types struct 的生成名）
    let mut candidates: HashSet<String> = HashSet::new();
    for p in &concerned {
        for layer in schema.prototype_chain(p) {
            candidates.insert(type_map::component_name(schema, &layer.base.name));
        }
    }
    for name in &struct_types {
        candidates.insert(type_map::component_name(schema, name));
    }
    let mut refs: HashSet<String> = HashSet::new();
    for p in &concerned {
        for layer in schema.prototype_chain(p) {
            refs.insert(type_map::component_name(schema, &layer.base.name));
            // 链上组件字段引用的嵌套类型也要收集（如 minable → MinableProperties）
            collect_refs(
                schema,
                config,
                &layer.base.name,
                &layer.properties,
                &candidates,
                &mut refs,
            );
        }
    }
    // 组合组件（如 IconComponent）及其字段引用的类型必须存活
    for c in &composites {
        refs.insert(format!("{}Component", c.name));
        collect_refs(
            schema,
            config,
            &c.name,
            &c.properties,
            &candidates,
            &mut refs,
        );
    }
    for name in &struct_types {
        let Some(t) = schema.type_def(name) else {
            continue;
        };
        collect_refs(
            schema,
            config,
            name,
            t.properties.as_deref().unwrap_or(&[]),
            &candidates,
            &mut refs,
        );
    }
    // 自定义类型覆盖：从候选集剔除（crate::types::X 由手写代码提供，不生成）。
    // 否则 extract_type_names 会从 "crate::types::BurnerEnergySource" 路径中
    // 词法提取出 BurnerEnergySource（∈ candidates）→ 误判为 live → 生成死类型。
    for (_, custom) in &config.custom_type_map {
        if let Some(tail) = custom.rsplit("::").next() {
            refs.remove(tail);
            candidates.remove(tail);
        }
    }
    let live_types: Vec<&String> = struct_types
        .iter()
        .filter(|name| refs.contains(&type_map::component_name(schema, name)))
        .collect();
    stats.nested_structs = live_types.len();

    // 4. 生成嵌套 struct 类型（仅活类型）
    let mut emitted: HashSet<String> = HashSet::new();
    for name in &live_types {
        let Some(t) = schema.type_def(name) else {
            continue;
        };
        let struct_name = type_map::component_name(schema, name);
        if !emitted.insert(struct_name.clone()) {
            continue;
        }
        out.push_str(&emit_struct(
            schema,
            config,
            name,
            &struct_name,
            t.properties.as_deref().unwrap_or(&[]),
            &composites,
            &mut stats,
        ));
    }

    // 5. 生成原型组件（每个原型继承链的每一层）
    for p in &concerned {
        let chain = schema.prototype_chain(p);
        for layer in chain.iter().rev() {
            let layer_name = type_map::component_name(schema, &layer.base.name);
            if emitted.insert(layer_name.clone()) {
                out.push_str(&emit_struct(
                    schema,
                    config,
                    &layer.base.name,
                    &layer_name,
                    &layer.properties,
                    &composites,
                    &mut stats,
                ));
            }
        }
    }
    // 6. 生成组合组件（如 IconComponent：由 detect_composites 检测出的重复字段组）
    for c in &composites {
        let comp_name = format!("{}Component", c.name);
        if emitted.insert(comp_name.clone()) {
            out.push_str(&emit_struct(
                schema,
                config,
                &c.name,
                &comp_name,
                &c.properties,
                &composites,
                &mut stats,
            ));
        }
    }
    stats.component_structs = emitted.len();

    // 5. 生成"原型 → 组件清单"注册表（COMPONENT_LIST）：
    //    继承链组件（根在前）+ 命中的组合组件（如 IconComponent，追加在末尾）。
    //    语义层可按清单统一遍历（如提取图标时只需找 IconComponent）。
    out.push_str("/// 关注原型（dump 顶层键）→ 其组件清单（继承链组件 + 组合组件，根在前）。\n");
    out.push_str("pub const COMPONENT_LIST: &[(&str, &[&str])] = &[\n");
    for p in &concerned {
        let Some(tn) = &p.typename else { continue };
        let chain = schema.prototype_chain(p);
        let mut names: Vec<String> = chain
            .iter()
            .rev()
            .map(|l| type_map::component_name(schema, &l.base.name))
            .collect();
        // 命中的组合组件追加到末尾（按配置顺序、去重）
        for c in &composites {
            if chain.iter().any(|l| c.layers.contains(&l.base.name)) {
                let comp_name = format!("{}Component", c.name);
                if !names.contains(&comp_name) {
                    names.push(comp_name);
                }
            }
        }
        out.push_str(&format!(
            "    ({tn:?}, &[{}]),\n",
            names
                .iter()
                .map(|n| format!("{n:?}"))
                .collect::<Vec<_>>()
                .join(", ")
        ));
    }
    out.push_str("];\n");

    // 5.5 生成 ComponentValue 枚举 + deserialize_component 分发（Phase 3）
    let mut all_components: Vec<String> = Vec::new();
    for p in &concerned {
        for layer in schema.prototype_chain(p) {
            let n = type_map::component_name(schema, &layer.base.name);
            if !all_components.contains(&n) {
                all_components.push(n);
            }
        }
    }
    for c in &composites {
        let n = format!("{}Component", c.name);
        if !all_components.contains(&n) {
            all_components.push(n);
        }
    }
    out.push_str("/// 全部组件变体（原型继承链层 + 组合组件）。\n");
    out.push_str("#[derive(Debug, Clone)]\npub enum ComponentValue {\n");
    for n in &all_components {
        out.push_str(&format!("    {n}({n}),\n"));
    }
    out.push_str("}\n\n");
    out.push_str("/// 按组件名反序列化（Phase 3 分发表）。\n");
    out.push_str(
        "pub fn deserialize_component(\n    name: &str,\n    value: &serde_json::Value,\n) -> Result<ComponentValue, serde_json::Error> {\n    match name {\n",
    );
    for n in &all_components {
        out.push_str(&format!(
            "        {n:?} => serde_json::from_value(value.clone()).map(ComponentValue::{n}),\n"
        ));
    }
    out.push_str("        _ => Err(serde::de::Error::custom(format!(\"未知组件名: {name}\"))),\n    }\n}\n\n");

    // 5.6 Component trait：组件类型安全的类型名 + 提取（Phase 3 强类型索引）
    out.push_str("/// 组件 trait：类型安全的组件名（&'static str）与提取。\n");
    out.push_str("pub trait Component: Sized {\n");
    out.push_str("    /// 组件名（COMPONENT_LIST 条目，也是 components map 的键）。\n");
    out.push_str("    const TYPENAME: &'static str;\n");
    out.push_str(
        "    /// 从 ComponentValue 按引用提取（类型不匹配时 panic——插入时已保证正确）。\n",
    );
    out.push_str("    #[track_caller]\n");
    out.push_str("    fn as_ref(cv: &ComponentValue) -> &Self;\n");
    out.push_str("    /// 从 ComponentValue 按引用提取（Option 版本）。\n");
    out.push_str("    fn as_ref_opt(cv: &ComponentValue) -> Option<&Self>;\n");
    out.push_str("}\n\n");
    for n in &all_components {
        out.push_str(&format!(
            "impl Component for {n} {{\n    const TYPENAME: &'static str = {n:?};\n    fn as_ref(cv: &ComponentValue) -> &Self {{\n        match cv {{\n            ComponentValue::{n}(c) => c,\n            _ => panic!(\"ComponentValue 类型不匹配: 期望 {n}\"),\n        }}\n    }}\n    fn as_ref_opt(cv: &ComponentValue) -> Option<&Self> {{\n        match cv {{\n            ComponentValue::{n}(c) => Some(c),\n            _ => None,\n        }}\n    }}\n}}\n\n"
        ));
    }

    // 5.7 PrototypeGroup 强类型枚举（关注类型 → 变体）+ 映射函数
    // 包进 pub mod 隔离：types 里可能有同名 struct（如 "Item"），顶层会撞名
    out.push_str("pub mod prototype_groups {\n");
    out.push_str("/// 聚合组（LuaPrototypes 的 entity/item 聚合语义）。\n");
    out.push_str("/// 关注类型各有独立变体；未知类型 → Unknown(原始 typename)。\n");
    out.push_str("#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]\npub enum PrototypeGroup {\n");
    out.push_str("    /// 含 EntityComponent 的原型。\n    Entity,\n");
    out.push_str("    /// 含 ItemComponent 的原型。\n    Item,\n");
    let mut group_variants: Vec<(&str, String)> = Vec::new(); // (typename, variant)
    for p in &concerned {
        let Some(tn) = &p.typename else { continue };
        let variant = typename_to_variant(tn);
        // 跳过聚合组及子类：Entity/Item 由组件推导；其子类（继承链含
        // EntityPrototype/ItemPrototype）实际归入 Entity/Item 组，不生成变体。
        if let Some(proto) = schema.prototype_by_typename(tn) {
            let chain_has = |name: &str| {
                schema
                    .prototype_chain(proto)
                    .iter()
                    .any(|l| l.base.name == name)
            };
            if variant == "Entity"
                || variant == "Item"
                || chain_has("EntityPrototype")
                || chain_has("ItemPrototype")
            {
                continue;
            }
        }
        if !group_variants.iter().any(|(t, _)| t == tn) {
            group_variants.push((tn, variant));
        }
    }
    for (_, variant) in &group_variants {
        out.push_str(&format!("    {variant},\n"));
    }
    out.push_str("}\n\n");
    out.push_str("/// typename（dump 键名）→ PrototypeGroup（未知类型 → Unknown）。\n");
    out.push_str("pub fn prototype_group_from_type(typename: &str) -> PrototypeGroup {\n    match typename {\n");
    // 聚合键：entity/item 顶层键直接归入聚合变体（与 derive_group 的组件判断一致）
    out.push_str("        \"entity\" => PrototypeGroup::Entity,\n        \"item\" => PrototypeGroup::Item,\n");
    for (tn, variant) in &group_variants {
        out.push_str(&format!("        {tn:?} => PrototypeGroup::{variant},\n"));
    }
    out.push_str("        // 不可达：store 只加载关注类型（COMPONENT_LIST 键）\n        _ => panic!(\"prototype_group_from_type: 未知 typename {typename:?}\"),\n    }\n}\n");
    out.push_str("} // mod prototype_groups\n\n");

    // 6. 自定义类型使用清单
    let mut custom_used: BTreeMap<String, ()> = BTreeMap::new();
    for (_, v) in &config.custom_type_map {
        if v != "serde_json::Value" {
            custom_used.insert(v.clone(), ());
        }
    }
    stats.custom_types_used = custom_used.into_keys().collect();

    (out, stats)
}

/// 从字段映射结果收集组件引用（死类型修剪的核心）。
/// 只收集"实际生成"的字段——被忽略的类型不会产生引用；
/// 字段级 Skip 规则的字段也不产生引用。
///
/// `candidates` 是全部潜在生成类型名（链层组件 + types struct），
/// 字段类型字符串中的词与候选集做交集——不能靠 "Component" 后缀判断
/// （types 里的普通 struct 生成原名，无后缀）。
fn collect_refs(
    schema: &Schema,
    config: &Config,
    schema_name: &str,
    props: &[Property],
    candidates: &HashSet<String>,
    refs: &mut HashSet<String>,
) {
    for prop in props {
        // 字段级覆盖：Skip 不产生引用；Type 引用手写类型（不在此收集）
        if let Some(action) = config.field_rule(schema_name, &prop.base.name) {
            match action {
                crate::config::FieldAction::Skip => continue,
                crate::config::FieldAction::Type(_) => continue,
            }
        }
        let mapped = type_map::map(schema, config, &prop.type_);
        collect_refs_from_mapped(&mapped, candidates, refs);
    }
}

/// 从 Mapped 中提取生成类型引用（与候选集交集）。
fn collect_refs_from_mapped(
    mapped: &type_map::Mapped,
    candidates: &HashSet<String>,
    refs: &mut HashSet<String>,
) {
    match mapped {
        type_map::Mapped::Rust(ty) => extract_type_names(ty, candidates, refs),
        type_map::Mapped::LenientInt(_) => {}
        type_map::Mapped::Array(inner) => collect_refs_from_mapped(inner, candidates, refs),
        type_map::Mapped::Dict(inner) => collect_refs_from_mapped(inner, candidates, refs),
        type_map::Mapped::Skipped => {}
    }
}

/// 从类型字符串提取生成类型名（与候选集交集，含 Vec<X>/BTreeMap<String, X>/元组）。
fn extract_type_names(ty: &str, candidates: &HashSet<String>, refs: &mut HashSet<String>) {
    let mut current = String::new();
    for ch in ty.chars() {
        if ch.is_ascii_alphanumeric() || ch == '_' {
            current.push(ch);
        } else {
            if candidates.contains(&current) {
                refs.insert(current.clone());
            }
            current.clear();
        }
    }
    if candidates.contains(&current) {
        refs.insert(current);
    }
}

/// typename（dump 键名，kebab-case）→ PrototypeGroup 变体名（PascalCase）。
fn typename_to_variant(typename: &str) -> String {
    let mut out = String::new();
    for part in typename.split('-') {
        let mut chars = part.chars();
        if let Some(first) = chars.next() {
            out.push(first.to_ascii_uppercase());
            out.extend(chars);
        }
    }
    if out.is_empty() {
        out.push_str("Unknown");
    }
    // Rust 关键字/非法标识符兜底（罕见）
    match out.as_str() {
        "Type" | "Match" | "Mod" | "Ref" | "Loop" | "Move" | "Use" | "Fn" | "In" | "As"
        | "Impl" | "Let" | "Mut" | "Pub" | "Self" | "Super" | "Where" | "While" | "Return"
        | "Static" | "Struct" | "Enum" | "Trait" | "True" | "False" | "Break" | "Continue"
        | "Const" | "Crate" | "Dyn" | "Else" | "Extern" | "For" | "If" | "Async" | "Await"
        | "Union" | "Unsafe" => format!("{out}_"),
        _ => out,
    }
}

/// 收集类型引用中的简单类型名（用于 struct 可达性收集）。
fn collect_type_names(t: &TypeRef, out: &mut Vec<String>) {
    match t {
        TypeRef::Simple(name) => out.push(name.clone()),
        TypeRef::Complex(c) => {
            if let Some(ComplexValue::TypeRef(v)) = &c.value {
                collect_type_names(v, out);
            }
            if let Some(k) = &c.key {
                collect_type_names(k, out);
            }
            if let Some(vs) = &c.values {
                for v in vs {
                    collect_type_names(v, out);
                }
            }
            if let Some(os) = &c.options {
                for o in os {
                    collect_type_names(o, out);
                }
            }
        }
    }
}

/// 生成一个完整结构体（字段 + 附属函数：默认值函数）。
fn emit_struct(
    schema: &Schema,
    config: &Config,
    schema_name: &str,
    struct_name: &str,
    props: &[Property],
    composites: &[Composite],
    stats: &mut GenStats,
) -> String {
    let mut fields = String::new();
    let mut helpers = String::new();

    // 组合字段组命中：组内字段被替换为 flatten 引用
    let composite = composites.iter().find(|c| c.layers.contains(schema_name));

    for prop in props {
        // 组合字段组的组内字段：不单独生成（由 flatten 的 Component 承载）
        if let Some(c) = &composite
            && c.fields.contains(&prop.base.name)
        {
            stats.skipped_fields += 1;
            continue;
        }
        // 文档注释（描述第一行 + schema 默认说明）
        let mut doc = String::new();
        let desc_first = prop.base.description.lines().next().unwrap_or("").trim();
        if !desc_first.is_empty() {
            doc.push_str(&format!("    /// {desc_first}\n"));
        }
        if let Some(DefaultValue::Text(text)) = &prop.default {
            let t = text.lines().next().unwrap_or("").trim();
            if !t.is_empty() {
                doc.push_str(&format!("    /// 默认(schema): {t}\n"));
            }
        }

        // 字段级覆盖规则（优先于类型级映射与忽略集）
        if let Some(action) = config.field_rule(schema_name, &prop.base.name) {
            match action {
                crate::config::FieldAction::Type(ty) => {
                    let field_name = rust_field_name(&prop.base.name);
                    let field_ty = if prop.optional {
                        format!("Option<{ty}>")
                    } else {
                        ty.to_string()
                    };
                    fields.push_str(&format!("{doc}    pub {field_name}: {field_ty},\n"));
                    stats.fields += 1;
                    continue;
                }
                crate::config::FieldAction::Skip => {
                    stats.skipped_fields += 1;
                    continue;
                }
            }
        }

        // 数组字段（含 array 类型别名展开）：宽松 Vec 处理
        let mapped = type_map::map(schema, config, &prop.type_);
        if let Mapped::Array(elem) = &mapped {
            let field_name = rust_field_name(&prop.base.name);
            let elem: &Mapped = elem;
            // 无 default 描述的数组字段：None 无语义（未设置 = 空数组），降为 Vec；
            // 有 default 描述（如 categories 默认 {"crafting"}）保留 Option 供 ext 回落。
            let optional = prop.optional && prop.default.is_some();
            match elem {
                // 元素被忽略 → 整个字段跳过
                Mapped::Skipped => {
                    stats.skipped_fields += 1;
                    continue;
                }
                // 整数元素数组：泛型宽松整数 Vec（serde 字面量替换）
                Mapped::LenientInt(_) => {
                    let fn_name = if optional {
                        "crate::lenient::de_opt_vec_int"
                    } else {
                        "crate::lenient::de_vec_int"
                    };
                    let field_ty = ty_str(&mapped, optional);
                    fields.push_str(&format!(
                        "{doc}    #[serde(deserialize_with = \"{fn_name}\")]\n    pub {field_name}: {field_ty},\n"
                    ));
                    stats.lenient_vec_fields += 1;
                }
                // 嵌套数组（Vec<Vec<X>>）或普通元素：泛型宽松 Vec（serde 字面量替换）
                _ => {
                    let fn_name = if optional {
                        "crate::lenient::de_opt_vec_lenient"
                    } else {
                        "crate::lenient::de_vec_lenient"
                    };
                    let field_ty = ty_str(&mapped, optional);
                    fields.push_str(&format!(
                        "{doc}    #[serde(deserialize_with = \"{fn_name}\")]\n    pub {field_name}: {field_ty},\n"
                    ));
                    stats.lenient_vec_fields += 1;
                }
            }
            continue;
        }

        // 非数组字段
        match mapped {
            Mapped::Skipped => {
                stats.skipped_fields += 1;
                continue;
            }
            Mapped::Array(_) => unreachable!("数组字段已在上方 Array 分支处理"),
            // 字典字段：BTreeMap<String, V>。无 default 描述的字典 None 无语义
            // （未设置 = 空 map，struct 级 #[serde(default)] 兜底），降为非 Option；
            // 有 default 描述保留 Option 供 ext 回落。
            Mapped::Dict(_) => {
                let field_name = rust_field_name(&prop.base.name);
                let optional = prop.optional && prop.default.is_some();
                let field_ty = ty_str(&mapped, optional);
                fields.push_str(&format!("{doc}    pub {field_name}: {field_ty},\n"));
                stats.fields += 1;
            }
            // 整数：宽松反序列化（serde 字面量替换泛型路径）
            Mapped::LenientInt(ty) => {
                let field_name = rust_field_name(&prop.base.name);
                let fn_name = if prop.optional {
                    "crate::lenient::de_opt_int"
                } else {
                    "crate::lenient::de_int"
                };
                let field_ty = if prop.optional {
                    format!("Option<{ty}>")
                } else {
                    ty.clone()
                };
                fields.push_str(&format!(
                    "{doc}    #[serde(deserialize_with = \"{fn_name}\")]\n    pub {field_name}: {field_ty},\n"
                ));
                stats.lenient_int_fields += 1;
            }
            Mapped::Rust(ty) => {
                let field_name = rust_field_name(&prop.base.name);
                // Literal 标量默认 → 锁定为非 Option + serde(default=fn)
                if let Some((v, _)) = literal_default(prop)
                    && let Some(expr) = default_expr(&v, &ty)
                {
                    let plain = field_name.trim_start_matches("r#");
                    let default_fn = format!("default_{struct_name}_{plain}");
                    fields.push_str(&format!(
                        "{doc}    #[serde(default = \"{default_fn}\")]\n    pub {field_name}: {ty},\n"
                    ));
                    helpers.push_str(&format!("fn {default_fn}() -> {ty} {{ {expr} }}\n"));
                    stats.locked_defaults += 1;
                } else {
                    let field_ty = if prop.optional {
                        format!("Option<{ty}>")
                    } else {
                        ty
                    };
                    if matches!(prop.default, Some(DefaultValue::Literal(_))) {
                        doc.push_str(&format!(
                            "    /// 默认(literal): {:?}\n",
                            prop.default.as_ref()
                        ));
                    }
                    fields.push_str(&format!("{doc}    pub {field_name}: {field_ty},\n"));
                }
                stats.fields += 1;
            }
        }
    }

    // 组合字段组：命中层以 flatten 引用组合 Component（保持 dump 平铺解析）
    // 暂时禁用，功能转移到单独的 Component 上
    // if let Some(c) = &composite {
    //     let field_name = c.name.to_lowercase();
    //     fields.push_str(&format!(
    //         "    #[serde(flatten)]\n    pub {field_name}: {}Component,\n",
    //         c.name
    //     ));
    // }

    let mut out = String::new();
    out.push_str(&format!(
        "#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n#[serde(default)]\npub struct {struct_name} {{\n{fields}}}\n"
    ));
    if !helpers.is_empty() {
        out.push_str(&helpers);
    }
    out.push('\n');
    out
}

/// 字段类型字符串（考虑 Option）。
fn ty_str(mapped: &Mapped, optional: bool) -> String {
    if let Mapped::Array(elem) = mapped {
        let inner = ty_str(elem, false);
        return if optional {
            format!("Option<Vec<{inner}>>")
        } else {
            format!("Vec<{inner}>")
        };
    }
    let ty = match mapped {
        Mapped::Rust(t) => t.clone(),
        Mapped::LenientInt(t) => t.clone(),
        Mapped::Skipped => "serde_json::Value".to_string(),
        Mapped::Array(_) => unreachable!("Array 已在上方处理"),
        Mapped::Dict(inner) => format!("BTreeMap<String, {}>", ty_str(inner, false)),
    };
    if optional {
        format!("Option<{ty}>")
    } else {
        ty
    }
}

/// 提取 Literal 标量默认值 → (Rust 表达式, 描述)。
/// 复杂字面值（null/数组/对象）返回 None（保持 Option）。
fn literal_default(prop: &Property) -> Option<(Value, String)> {
    let Some(DefaultValue::Literal(lit)) = &prop.default else {
        return None;
    };
    let v = lit.value.clone()?;
    match v {
        Value::Bool(_) | Value::Number(_) | Value::String(_) => Some((v.clone(), v.to_string())),
        _ => None,
    }
}

/// 按字段类型生成默认值表达式。
fn default_expr(v: &Value, ty: &str) -> Option<String> {
    match (v, ty) {
        (Value::Bool(b), "serde_json::Value") => Some(format!("serde_json::Value::Bool({b})")),
        (Value::Number(n), "serde_json::Value") => Some(format!("serde_json::Value::from({n})")),
        (Value::String(s), "serde_json::Value") => {
            Some(format!("serde_json::Value::String({s:?}.into())"))
        }
        // 仅对原生标量类型锁定默认值；自定义/嵌套类型保持 Option
        (Value::Bool(b), "bool") => Some(b.to_string()),
        // 数字默认值：JSON 的 0 是整数，需要类型后缀才能作为 f64/f32 返回
        (Value::Number(n), "f64") => Some(format!("{n}f64")),
        (Value::Number(n), "f32") => Some(format!("{n}f32")),
        (Value::String(s), "String") => Some(format!("{s:?}.to_string()")),
        _ => None,
    }
}

/// 字段名 → Rust 合法标识符（Rust 关键字加 r#）。
fn rust_field_name(name: &str) -> String {
    match name {
        "match" | "mod" | "ref" | "move" | "loop" | "use" | "fn" | "in" | "as" | "impl" | "let"
        | "mut" | "pub" | "self" | "Self" | "super" | "where" | "while" | "return" | "static"
        | "struct" | "enum" | "trait" | "true" | "false" | "break" | "continue" | "const"
        | "crate" | "dyn" | "else" | "extern" | "for" | "if" | "async" | "await" | "box" | "do"
        | "abstract" | "final" | "override" | "priv" | "typeof" | "unsized" | "virtual"
        | "yield" | "try" | "macro_rules" | "union" | "unsafe" | "type" => {
            format!("r#{name}")
        }
        _ => name.to_string(),
    }
}
