//! Rust 代码生成：组件结构体 + 原型注册表。

use crate::config::Config;
use crate::schema::{Prototype, Schema, TypeRef};
use crate::type_map::{self, Mapped};
use std::collections::{BTreeMap, HashSet};

/// 生成统计（供自检测试断言）。
#[derive(Debug, Clone, Default)]
pub struct GenStats {
    /// 生成的原型（含继承链上的抽象层）组件数。
    pub component_structs: usize,
    /// 生成的嵌套 struct 类型数。
    pub nested_structs: usize,
    /// 生成的字段总数。
    pub fields: usize,
    /// 跳过的字段数（忽略类型 / literal / 无法映射）。
    pub skipped_fields: usize,
    /// 关注的原型类型数（dump 顶层键）。
    pub concerned_typenames: usize,
    /// 生成时依赖的自定义类型名集合（如 EnergyAmount）。
    pub custom_types_used: Vec<String>,
}

/// 生成器入口：返回生成的 Rust 代码文本与统计。
pub fn generate(schema: &Schema, config: &Config) -> (String, GenStats) {
    let mut stats = GenStats::default();
    let mut out = String::new();

    out.push_str("// @generated by metatorio-data-codegen — DO NOT EDIT.\n");
    out.push_str("// 来源: prototype-api.json (");
    out.push_str(&schema.application_version);
    out.push_str(", api_version ");
    out.push_str(&schema.api_version.to_string());
    out.push_str(")\n\n");
    out.push_str("use serde::{Deserialize, Serialize};\n\n");

    // 1. 收集关注原型（按 typename）
    let mut concerned: Vec<&Prototype> = Vec::new();
    for tn in &config.concerned_typenames {
        if let Some(p) = schema.prototype_by_typename(tn) {
            if !concerned.iter().any(|x| x.base.name == p.base.name) {
                concerned.push(p);
            }
        }
    }
    stats.concerned_typenames = concerned.len();

    // 2. 收集可达 struct 类型（从所有关注原型的字段类型出发）
    let mut type_roots: Vec<String> = Vec::new();
    for p in &concerned {
        for layer in schema.prototype_chain(p) {
            for prop in &layer.properties {
                collect_type_names(&prop.type_, &mut type_roots);
            }
        }
    }
    let struct_types = type_map::collect_struct_types(schema, config, type_roots.iter().map(|s| s.as_str()));
    stats.nested_structs = struct_types.len();

    // 3. 生成嵌套 struct 类型
    // 按依赖排序（简单的拓扑：重复生成直到稳定——Phase 1 用两遍法：先收集所有名字，再生成）
    let mut emitted: HashSet<String> = HashSet::new();
    for name in &struct_types {
        let Some(t) = schema.type_def(name) else { continue };
        let struct_name = type_map::component_name(name);
        if !emitted.insert(struct_name.clone()) {
            continue;
        }
        let fields = emit_struct_fields(schema, config, t.properties.as_deref().unwrap_or(&[]), &mut stats);
        out.push_str(&format!(
            "#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n#[serde(default)]\npub struct {struct_name} {{\n{fields}}}\n\n"
        ));
    }

    // 4. 生成原型组件（每个原型继承链的每一层）
    let mut layer_names: Vec<String> = Vec::new();
    for p in &concerned {
        let chain = schema.prototype_chain(p);
        // 链：自身 → ... → PrototypeBase
        for layer in chain.iter().rev() {
            let layer_name = type_map::component_name(&layer.base.name);
            if emitted.insert(layer_name.clone()) {
                let fields = emit_struct_fields(schema, config, &layer.properties, &mut stats);
                out.push_str(&format!(
                    "#[derive(Debug, Clone, Default, Serialize, Deserialize)]\n#[serde(default)]\npub struct {layer_name} {{\n{fields}}}\n\n"
                ));
            }
            layer_names.push(layer_name);
        }
    }
    stats.component_structs = emitted.len();

    // 5. 生成"原型 → 继承链组件"注册表
    out.push_str("/// 关注原型（dump 顶层键）→ 其继承链组件名（根在前）。\n");
    out.push_str("pub const PROTOTYPE_CHAINS: &[(&str, &[&str])] = &[\n");
    for p in &concerned {
        let Some(tn) = &p.typename else { continue };
        let chain = schema.prototype_chain(p);
        let names: Vec<String> = chain
            .iter()
            .rev()
            .map(|l| type_map::component_name(&l.base.name))
            .collect();
        out.push_str(&format!(
            "    ({tn:?}, &[{}]),\n",
            names.iter().map(|n| format!("{n:?}")).collect::<Vec<_>>().join(", ")
        ));
    }
    out.push_str("];\n");

    // 6. 自定义类型使用清单（供依赖方生成辅助代码）
    let mut custom_used: BTreeMap<String, ()> = BTreeMap::new();
    for (k, v) in &config.custom_type_map {
        if v != "serde_json::Value" {
            custom_used.insert(v.clone(), ());
        }
        let _ = k;
    }
    stats.custom_types_used = custom_used.into_keys().collect();

    (out, stats)
}

/// 收集类型引用中的简单类型名（用于 struct 可达性收集）。
fn collect_type_names(t: &TypeRef, out: &mut Vec<String>) {
    match t {
        TypeRef::Simple(name) => out.push(name.clone()),
        TypeRef::Complex(c) => {
            if let Some(crate::schema::ComplexValue::TypeRef(v)) = &c.value {
                collect_type_names(v, out);
            }
            if let Some(k) = &c.key {
                collect_type_names(k, out);
            }
            if let Some(vs) = &c.values {
                for v in vs {
                    collect_type_names(v, out);
                }
            }
            if let Some(os) = &c.options {
                for o in os {
                    collect_type_names(o, out);
                }
            }
        }
    }
}

/// 生成结构体字段列表。
fn emit_struct_fields(
    schema: &Schema,
    config: &Config,
    props: &[crate::schema::Property],
    stats: &mut GenStats,
) -> String {
    let mut fields = String::new();
    for prop in props {
        let mapped = type_map::map(schema, config, &prop.type_);
        match mapped {
            Mapped::Skipped => {
                stats.skipped_fields += 1;
                continue;
            }
            Mapped::Rust(ty) => {
                let field_name = rust_field_name(&prop.base.name);
                let ty = if prop.optional { format!("Option<{ty}>") } else { ty };
                // alt_name 支持
                let alias = prop
                    .alt_name
                    .as_ref()
                    .map(|a| format!("    #[serde(alias = {a:?})]\n"))
                    .unwrap_or_default();
                fields.push_str(&format!("    {alias}    pub {field_name}: {ty},\n"));
                stats.fields += 1;
            }
        }
    }
    fields
}

/// 字段名 → Rust 合法标识符（Rust 关键字加 r#）。
fn rust_field_name(name: &str) -> String {
    match name {
        "type" => "r#type".to_string(),
        "match" | "mod" | "ref" | "move" | "loop" | "use" | "fn" | "in" | "as" | "impl"
        | "let" | "mut" | "pub" | "self" | "Self" | "super" | "where" | "while" | "return"
        | "static" | "struct" | "enum" | "trait" | "true" | "false" | "break" | "continue"
        | "const" | "crate" | "dyn" | "else" | "extern" | "for" | "if" | "async" | "await"
        | "box" | "do" | "abstract" | "final" | "override" | "priv" | "typeof" | "unsized"
        | "virtual" | "yield" | "try" | "macro_rules" | "union" | "unsafe" => {
            format!("r#{name}")
        }
        _ => name.to_string(),
    }
}
